logging.level.br.com=DEBUG
queue1.name=orquestracao_pedidos_saga_reply
queue2.name=orquestracao_pagamentos
server.port=8082
spring.application.name=Cobranca Service
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=ola
spring.datasource.password=mundo
spring.datasource.url=jdbc:h2:file:D:/Estudos/FIAP - Arquitetura de Software/4.5 - SAGA Pattern/database_projeto/cobrancaDB;mode=PostgreSQL;AUTO_SERVER=TRUE
spring.h2.console.enabled=true
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.defer-datasource-initialization=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.rabbitmq.host=localhost
spring.rabbitmq.password=guest
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
springdoc.swagger-ui.path=/doc
